from __future__ import annotations

from pathlib import Path
from typing import Any
import re


def build_professional_cover_letter(
    job: dict[str, Any],
    profile: dict[str, Any] | str,
    tone: str = "confident",
) -> str:
    """Generate a conservative, profile-backed cover letter draft."""
    title = job.get("title") or "the role"
    company = job.get("company") or "the company"
    profile_summary = _profile_summary(profile)
    keywords = _profile_keywords(profile)

    opening = f"Dear Hiring Team,\n\nI am excited to apply for the {title} position at {company}."
    body = (
        f"My background includes {profile_summary}. "
        f"The areas I would emphasize for this opportunity are {', '.join(keywords) if keywords else 'the experience documented in my profile'}. "
        "I would focus on making the application truthful, specific to the role, and grounded in evidence from my work."
    )
    closer = (
        f"I would welcome the opportunity to discuss how my experience can contribute to {company}. "
        "Thank you for your time and consideration."
    )

    if tone == "warm":
        closer = closer.replace("would welcome", "would be delighted to have")

    return f"{opening}\n\n{body}\n\n{closer}\n\nBest regards"


def build_cover_letter_payload(job: dict[str, Any], profile: dict[str, Any] | str) -> dict[str, Any]:
    """Create a structured payload for a cover letter workflow."""
    title = job.get("title") or "Role"
    company = job.get("company") or "the company"
    keywords = _profile_keywords(profile)

    research_summary = (
        f"Research summary for {company}: review product, team context, market, and role-specific needs before final use."
    )

    return {
        "job": job,
        "profile": profile,
        "research_summary": research_summary,
        "keyword_alignment": keywords,
        "angle_prompts": {
            "why": f"Why is this profile a truthful fit for {title} at {company}?",
            "problems": "What business, product, operational, or domain problems would this candidate help solve?",
            "approach": "How would this candidate approach delivery and collaboration?",
            "tone": "What tone fits this company, role, and application channel?",
        },
        "approval_gate": {
            "ready_for_review": True,
            "review_prompt": "Review the draft, adjust tone, and confirm every claim is supported by the candidate profile.",
        },
        "draft": build_professional_cover_letter(job, profile),
        "professional_template": {
            "subject": f"Application for {title} at {company}",
            "tone": "confident",
        },
    }


def export_cover_letter_pdf(text: str, output_path: str | Path) -> bool:
    """Export simple text content to PDF using reportlab with a polished layout."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except ModuleNotFoundError as exc:
        raise RuntimeError("PDF export requires reportlab. Install it with `pip install reportlab`.") from exc

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(path), pagesize=letter)
    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0.12, 0.14, 0.18)

    y = 750
    for line in text.splitlines():
        c.drawString(40, y, line[:110])
        y -= 14
        if y < 60:
            c.showPage()
            y = 750

    c.setFont("Helvetica-Bold", 10)
    c.drawString(40, 40, "Generated by Job Orchestrator")
    c.save()
    return path.exists()


def _profile_summary(profile: dict[str, Any] | str) -> str:
    if isinstance(profile, str):
        return profile.splitlines()[0] if profile.strip() else "the experience documented in my profile"
    headline = str(profile.get("headline") or "").strip()
    roles = [str(role) for role in [*profile.get("target_roles", []), *profile.get("secondary_roles", [])] if str(role).strip()]
    if headline and roles:
        return f"{headline}, with target alignment toward {', '.join(roles[:3])}"
    if headline:
        return headline
    if roles:
        return f"target alignment toward {', '.join(roles[:3])}"
    return "the experience documented in my profile"


def _profile_keywords(profile: dict[str, Any] | str) -> list[str]:
    if isinstance(profile, str):
        stopwords = {"with", "and", "the", "for", "from", "that", "this", "have", "experience"}
        words = []
        for word in re.findall(r"[A-Za-z][A-Za-z0-9+#.-]{2,}", profile):
            key = word.lower()
            if key not in stopwords and key not in {item.lower() for item in words}:
                words.append(word)
        return words[:6]
    return [
        str(skill.get("name") or "").strip()
        for skill in profile.get("skills") or []
        if isinstance(skill, dict) and str(skill.get("name") or "").strip()
    ][:6]
