from __future__ import annotations

from pathlib import Path
from typing import Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def build_professional_cover_letter(job: Dict[str, Any], profile: str, tone: str = "confident") -> str:
    """Generate a more polished cover letter draft for direct use."""
    title = job.get("title") or "the role"
    company = job.get("company") or "the company"
    description = job.get("description") or ""
    keywords = [k for k in ["python", "backend", "api", "aws", "postgres", "leadership", "mentoring"] if k in description.lower()]
    if not keywords:
        keywords = ["software delivery", "technical ownership"]

    opening = f"Dear Hiring Team,\n\nI am excited to apply for the {title} position at {company}."
    body = (
        f"My background in {', '.join(keywords)} and my experience delivering reliable, scalable products "
        f"make me a strong fit for this opportunity. I enjoy building pragmatic solutions, collaborating "
        f"with cross-functional teams, and taking ownership of end-to-end delivery."
    )
    closer = (
        f"I would welcome the opportunity to discuss how I can contribute to {company} and help drive impact "
        f"in this role. Thank you for your time and consideration."
    )

    if tone == "warm":
        body = body.replace("strong fit", "natural fit")
        closer = closer.replace("would welcome", "would be delighted to")

    signature = profile.splitlines()[0] if profile else "Your Name"
    return f"{opening}\n\n{body}\n\n{closer}\n\nBest regards,\n{signature}"


def build_cover_letter_payload(job: Dict[str, Any], profile: str) -> Dict[str, Any]:
    """Create a structured payload for an advanced cover letter workflow."""
    title = job.get("title") or "Role"
    company = job.get("company") or "the company"
    description = job.get("description") or ""

    keywords = []
    for token in ["python", "backend", "api", "aws", "postgres", "leadership", "mentoring"]:
        if token in description.lower():
            keywords.append(token)

    research_summary = (
        f"Research summary for {company}: focus on product, engineering maturity, and role context."
    )

    return {
        "job": job,
        "profile": profile,
        "research_summary": research_summary,
        "keyword_alignment": keywords or ["backend", "delivery"],
        "angle_prompts": {
            "why": f"Why am I a strong fit for {title} at {company}?",
            "problems": "What business or product problems would I solve?",
            "approach": "How would I approach delivery and collaboration?",
            "tone": "What tone fits this company and role?",
        },
        "approval_gate": {
            "ready_for_review": True,
            "review_prompt": "Review the draft, adjust the tone, and confirm whether the experience and keywords are well reflected.",
        },
        "draft": build_professional_cover_letter(job, profile),
        "professional_template": {
            "subject": f"Application for {title} at {company}",
            "tone": "confident",
        },
    }


def export_cover_letter_pdf(text: str, output_path: str | Path) -> bool:
    """Export simple text content to PDF using reportlab with a more polished layout."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(path), pagesize=letter)
    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0.12, 0.14, 0.18)

    y = 750
    for line in text.splitlines():
        c.drawString(40, y, line[:110])
        y -= 14
        if y < 60:
            c.showPage()
            y = 750

    c.setFont("Helvetica-Bold", 10)
    c.drawString(40, 40, "Generated by Job Orchestrator")
    c.save()
    return path.exists()
